import Link from "next/link";
import "../globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
